# Generated by Django 3.0.7 on 2021-04-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210421_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google_plus',
            new_name='google_plus_link',
        ),
    ]
