# Generated by Django 3.0.7 on 2021-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20210423_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
