# Generated by Django 3.0.7 on 2021-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_auto_20210423_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(),
        ),
    ]
